version: "3.7"
services: 
  postgres:
      container_name: postgres-app
      image: postgres:latest
      ports: 
        - "5432:5432"
      volumes: 
        - ./pg-data:/var/lib/postgresql/data
      networks: 
        - netnet
      environment: 
        - POSTGRES_USER=zayyan
        - POSTGRES_PASSWORD=abcde
        - POSTGRES_DB=store

  # pgadmin:
  #    container_name: pgadmin-app
  #    image: dpage/pgadmin4
  #    ports:
  #       - "6789:80"
  #    environment:
  #       PGADMIN_DEFAULT_EMAIL: admin@example.com
  #       PGADMIN_DEFAULT_PASSWORD: root
  #    restart: unless-stopped
  #    networks:
  #       - netnet

  redis:
      container_name: redis-app
      image: redis:alpine3.12
      command: redis-server
      environment: 
        - REDIS_PORT=6379
      ports:  
        - "6379:6379"
      networks: 
        - netnet
      volumes: 
        - ./redis-data:/data

  backend:
      image: docker:backend
      ports: 
          - "8282-8283:3000"
      environment: 
          - DBUSER=zayyan
          - DBPASSWORD=abcde
          - DBNAME=store
          - DBHOST=postgres
          - DBPORT=5432
          - JWT_KEYS=inipenting
          - CLOUD_KEY=412362658317893
          - CLOUD_SECRET=27eUzpLSevhyuwu6f0bmoQypfNg
          - CLOUD_NAME=yayanjay
          - REDIS_HOST=redis
          - REDIS_PORT=6379
      deploy:
       mode: replicated
       replicas: 2
       resources:
         limits:
           cpus: "0.50"
           memory: 50M
      networks: 
          - netnet
      depends_on: 
          - postgres

networks: 
    netnet:
        driver: bridge

volumes: 
    pg-data:
    redis-data: